@url=http://localhost:3000

### Obtener todos los conductores
GET {{url}}/conductores

### Crear un nuevo vehiculo 
POST {{url}}/conductores
Content-Type: application/json

{
   "nombre": "nazareno",
   "apellido": "mansilla",
   "dni": "46985403",
   "licencia": "A2",
   "vencimiento_licencia": "2025-11-1"
}

### Crear un nuevo conductor
PUT {{url}}/conductores/2
Content-Type: application/json

{
   "nombre": "pedro",
   "apellido": "luque",
   "dni": "43567856",
   "licencia": "A1",
   "vencimiento_licencia": "2025-11-3"
}