@url=http://localhost:3000


### Obtener todos los conductores
GET {{url}}/conductores

### Obtener los kilometros hecho por un conductor
GET {{url}}/conductores/kilometros/1

### Crear un nuevo conductor
POST {{url}}/conductores
Content-Type: application/json

{
   "nombre": "elio",
   "apellido": "pilot",
   "dni": "43567835",
   "licencia": "comun",
   "vencimiento_licencia": "2025-12-25"
}

### Actualizar un conductor
PUT {{url}}/conductores/2
Content-Type: application/json

{
   "nombre": "elio",
   "apellido": "pilot",
   "dni": "43567835",
   "licencia": "profesional",
   "vencimiento_licencia": "2025-12-25"
}

### Eliminar un conductor
DELETE {{url}}/conductores/2