@url=http://localhost:3000

### Obtener todos los conductores
GET {{url}}/conductores

###
GET {{url}}/conductores/kilometros/1

### Crear un nuevo vehiculo 
POST {{url}}/conductores
Content-Type: application/json

{
   "nombre": "santino",
   "apellido": "pilot",
   "dni": "47212835",
   "licencia": "A2",
   "vencimiento_licencia": "2026-01-17"
}

### Crear un nuevo conductor
PUT {{url}}/conductores/1
Content-Type: application/json

{
   "nombre": "santino",
   "apellido": "pilot",
   "dni": "46212835",
   "licencia": "A1",
   "vencimiento_licencia": "2026-01-20"
}

### Eliminar un vehiculo
DELETE {{url}}/conductores/6