@url=http://localhost:3000

### Registro
POST {{url}}/usuarios/registro
Content-Type: application/json

{
    "nombre": "santino",
    "email": "santino.pilot@gmail.com",
    "contrasenia": "s1234567"
}

### Login
POST {{url}}/usuarios/login
Content-Type: application/json

{
    "email": "santino.pilot@gmail.com",
    "contrasenia": "s1234567"
}

