@url=http://localhost:3000

### Registro
POST {{url}}/usuarios/registro
Content-Type: application/json

{
    "nombre": "Elio",
    "email": "eliopilot@gmail.com",
    "contrasenia": "admin1234"
}

### Login
POST {{url}}/usuarios/login
Content-Type: application/json

{
    "email": "eliopilot@gmail.com",
    "contrasenia": "admin1234"
}

