@url=http://localhost:3000

### Consultar todos los vehiculos
GET {{url}}/vehiculos

###
GET {{url}}/vehiculos/kilometros/1

### Crear un nuevo vehiculo 
POST {{url}}/vehiculos
Content-Type: application/json

{
    "marca": "fiat",
    "modelo": "siena 12",
    "patente": "pap 345", 
    "anio": 2017,
    "capacidad_carga": 200
}

### Actualizar un vehiculo ya existente
PUT {{url}}/vehiculos/18
Content-Type: application/json

{
    "marca": "corolla",
    "modelo": "xei",
    "patente": "ehb 385", 
    "anio": 2009,
    "capacidad_carga": 150
}

### Eliminar un vehiculo
DELETE {{url}}/vehiculos/18