@url=http://localhost:3000

### Consultar todos los vehiculos
GET {{url}}/vehiculos

### Crear un nuevo vehiculo 
POST {{url}}/vehiculos
Content-Type: application/json

{
    "marca": "mercedes benz",
    "modelo": "t340",
    "patente": "tremp3", 
    "anio": "2019",
    "capacidad_carga": 500
}

### Actualizar un vehiculo ya existente
PUT {{url}}/vehiculos/1
Content-Type: application/json

{
    "marca": "corolla",
    "modelo": "xei",
    "patente": "pap 234", 
    "anio": "2009",
    "capacidad_carga": 150
}