@url=http://localhost:3000

### Consultar todos los vehiculos
GET {{url}}/vehiculos

### Obtener los km totales de un vehiculo
GET {{url}}/vehiculos/kilometros/1

### Crear un nuevo vehiculo 
POST {{url}}/vehiculos
Content-Type: application/json

{
    "marca": "ford",
    "modelo": "mustang",
    "patente": "hrt 354", 
    "anio": 2024,
    "capacidad_carga": 400
}

### Actualizar un vehiculo
PUT {{url}}/vehiculos/1
Content-Type: application/json

{
    "marca": "fiat",
    "modelo": "siena 12",
    "patente": "h43 354", 
    "anio": 2017,
    "capacidad_carga": 150
}

### Eliminar un vehiculo
DELETE {{url}}/vehiculos/1